### ISSUE TITLE
Specifying scan and copy performance options cause exceptions

### ISSUE THREAD

**Issue by dabadab** [andrebrait/DATROMTool#4]
version: b803e3e commit

Specifying either --scan-threads, --scan-buffer, --scan-max-buffer or --copy-raw-zip results in the exception:

```
java.lang.NullPointerException: Cannot invoke "io.github.datromtool.cli.option.PerformanceOptions$ForceOptions.isForceUnrar()" because "this.forceOptions" is null
	at io.github.datromtool.cli.option.PerformanceOptions.merge(PerformanceOptions.java:169)
	at io.github.datromtool.cli.command.OneGameOneRomCommand.call(OneGameOneRomCommand.java:125)
	at io.github.datromtool.cli.command.OneGameOneRomCommand.call(OneGameOneRomCommand.java:45)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at io.github.datromtool.cli.DatRomCommand.main(DatRomCommand.java:31)
```

If --force-unrar is also specified these exceptions do not appear.

Specifying --copy-threads causes a different exception that is not fixed by --force-unrar:

```
java.lang.NullPointerException: threads is marked non-null but is null
	at io.github.datromtool.config.AppConfig$FileCopierConfig$FileCopierConfigBuilder.threads(AppConfig.java:55)
	at io.github.datromtool.cli.option.PerformanceOptions.merge(PerformanceOptions.java:185)
	at io.github.datromtool.cli.command.OneGameOneRomCommand.call(OneGameOneRomCommand.java:126)
	at io.github.datromtool.cli.command.OneGameOneRomCommand.call(OneGameOneRomCommand.java:45)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at io.github.datromtool.cli.DatRomCommand.main(DatRomCommand.java:31)
```

**Comment by andrebrait** [comment]
Thanks for reporting it.
I'll fix it soon.
